# Validation Analysis

In [1]:
import pandas as pd
# Cargar el CSV
df = pd.read_csv("data_lake/reports/latest/raw_issues.csv")
# Contar cuántos símbolos DISTINTOS hay en total
total_simbolos = df["symbol"].nunique()
print(f"Símbolos únicos: {total_simbolos}")
# Si quieres ver qué símbolos hay y cuántas veces se repite cada uno:
conteo_simbolos = df["symbol"].value_counts()
print(conteo_simbolos)

Símbolos únicos: 15
symbol
A      1
AMP    1
AVY    1
CMI    1
HLT    1
HWM    1
MLM    1
NVR    1
PH     1
SWK    1
TDG    1
TEL    1
TGT    1
TPR    1
UHS    1
Name: count, dtype: int64

In [2]:
df.head(9)

  symbol        date                  issue severity        value
0      A  2026-04-08  open_outside_high_low    error   116.919998
1    AMP  2026-04-08  open_outside_high_low    error   453.100006
2    AVY  2026-04-08  open_outside_high_low    error   175.309998
3    CMI  2026-04-08  open_outside_high_low    error   596.650024
4    HLT  2026-04-08  open_outside_high_low    error   317.200012
5    HWM  2026-04-08  open_outside_high_low    error   250.000000
6    MLM  2026-04-08  open_outside_high_low    error   624.359985
7    NVR  2026-04-08  open_outside_high_low    error  6755.500000
8     PH  2026-04-08  open_outside_high_low    error   966.049988

In [3]:
df_error = df[df.severity == 'error']

In [4]:
df_error.tail(30)

   symbol        date                  issue severity        value
0       A  2026-04-08  open_outside_high_low    error   116.919998
1     AMP  2026-04-08  open_outside_high_low    error   453.100006
2     AVY  2026-04-08  open_outside_high_low    error   175.309998
3     CMI  2026-04-08  open_outside_high_low    error   596.650024
4     HLT  2026-04-08  open_outside_high_low    error   317.200012
5     HWM  2026-04-08  open_outside_high_low    error   250.000000
6     MLM  2026-04-08  open_outside_high_low    error   624.359985
7     NVR  2026-04-08  open_outside_high_low    error  6755.500000
8      PH  2026-04-08  open_outside_high_low    error   966.049988
9     SWK  2026-04-08  open_outside_high_low    error    71.489998
10    TDG  2026-04-08  open_outside_high_low    error  1219.880005
11    TEL  2026-04-08  open_outside_high_low    error   223.029999
12    TGT  2026-04-08  open_outside_high_low    error   123.120003
13    TPR  2026-04-08  open_outside_high_low    error   150.570007
14    UHS  2026-04-08  open_outside_high_low    error   186.759995

In [5]:
df_error.symbol.nunique()

15