# Cargar OHLCV de todas las coins desde Qlib

Este notebook carga la serie de precios (Open/High/Low/Close/Volume) de **todas las coins** del universo crypto directamente desde el dataset **Qlib** (no desde CSV), usando `qlib.data.D.features()`.

- **Datos:** `data/qlib` (formato binario Qlib `.bin`)
- **Universo:** `data/qlib/instruments/crypto.txt`
- **Campo por defecto muestra:** OHLCV (`$open`, `$high`, `$low`, `$close`, `$volume`)

> Requiere el kernel Python del venv `qlib-venv` (donde está instalado `qlib`).

## 1. Inicializar Qlib

Inicializamos Qlib contra el dataset `data/qlib` (mismo provider y región que usa `qlib_sfm_pipeline.v8.py`).

In [1]:
from pathlib import Path

import qlib
from qlib.config import REG_US
from qlib.data import D

# --- Resuelve el repo raíz (/opt/data/qlib) aunque el notebook se abra
# desde el kernel en otra carpeta (p.ej. nbconvert, Jupyter Lab en otro dir)
PROJECT_ROOT = Path.cwd()
# Sube directorios si no estamos en la raíz del repo (presencia de data/qlib)
for _ in range(5):
    if (PROJECT_ROOT / "data" / "qlib" / "instruments").is_dir():
        break
    PROJECT_ROOT = PROJECT_ROOT.parent

PROVIDER_URI = PROJECT_ROOT / "data" / "qlib"   # mismo provider/región que el pipeline SFM v8
FIELDS = ["$open", "$high", "$low", "$close", "$volume"]

qlib.init(provider_uri=str(PROVIDER_URI), region=REG_US, kernels=1)
print("Qlib inicializado OK →", PROVIDER_URI)

[109306:MainThread](2026-09-01 20:57:15,288) INFO - qlib.Initialization - [config.py:473] - default_conf: client.

[109306:MainThread](2026-09-01 20:57:17,134) INFO - qlib.Initialization - [__init__.py:82] - qlib successfully initialized based on client settings.

[109306:MainThread](2026-09-01 20:57:17,135) INFO - qlib.Initialization - [__init__.py:84] - data_path={'__DEFAULT_FREQ': PosixPath('/opt/data/qlib/data/qlib')}

Qlib inicializado OK → /opt/data/qlib/data/qlib

## 2. Universo de coins

Leemos el universo declarado desde `instruments/crypto.txt` (cada línea: `simbolo\tfecha_inicio\tfecha_fin`).

In [2]:
instruments_path = PROJECT_ROOT / "data" / "qlib" / "instruments" / "crypto.txt"
coins = []
for line in instruments_path.read_text().splitlines():
    if line.strip() and not line.startswith("#"):
        coins.append(line.split("\t")[0])

print(f"{len(coins)} coins en el universo:")
print("  " + ", ".join(sorted(coins)))

9 coins en el universo:
  ada, btc, doge, eth, link, ltc, sol, xlm, xrp

## 3. Cargar cada coin en pandas y mostrar head/tail

Para **cada coin** cargamos su tabla OHLCV desde Qlib con `D.features()` y mostramos:
- **head(3)** → primeras 3 filas **reales** (desde la fecha de lanzamiento de la coin, no desde ceros de padding)
- **tail(3)** → últimas 3 filas
- rango de fechas, nº de filas y precio de apertura/cierre

> Nota: el dataset Qlib rellena con `0.0` los días previos al lanzamiento de cada coin (antes de su primera fecha en `crypto.txt`). Para que el `head` sea útil, cargamos cada coin desde su propia fecha de inicio.

In [3]:
# Fecha real de inicio de cada coin (desde crypto.txt): simbolo, inicio, fin
start_by_coin = {}
for line in instruments_path.read_text().splitlines():
    if line.strip() and not line.startswith("#"):
        parts = line.split("\t")
        start_by_coin[parts[0]] = parts[1]

dataframes = {}

for coin in sorted(coins):
    start = start_by_coin[coin]
    df = D.features([coin], FIELDS, start_time=start, end_time="2026-12-31")
    # Suelta el nivel extra del MultiIndex por si solo hay un instrumento
    df = df.droplevel("instrument", axis=0) if "instrument" in df.index.names else df
    dataframes[coin] = df

    print("=" * 68)
    print(f"  {coin.upper()}")
    print("=" * 68)
    print(f"  Filas: {len(df)}  |  Rango: {df.index[0].date()} → {df.index[-1].date()}")
    display(df.head(3))
    print("  " + "·" * 60 + "  …")
    display(df.tail(3))
    print()

print(f"✅ Cargadas {len(dataframes)} coins en el dict `dataframes`.")

====================================================================
  ADA
====================================================================
  Filas: 3059  |  Rango: 2018-04-17 → 2026-08-31

              $open   $high     $low   $close     $volume
datetime
2018-04-17  0.25551  0.2880  0.23983  0.24260  67462296.0
2018-04-18  0.24260  0.2646  0.24201  0.26200  31328096.0
2018-04-19  0.26199  0.2750  0.25777  0.27004  50859980.0

  ····························································  …

               $open     $high      $low    $close      $volume
datetime
2026-08-29  0.203100  0.203500  0.198900  0.201800   46623256.0
2026-08-30  0.201800  0.206100  0.189400  0.192700  111173584.0
2026-08-31  0.212376  0.217739  0.190268  0.192917          0.0

====================================================================
  BTC
====================================================================
  Filas: 3302  |  Rango: 2017-08-17 → 2026-08-31

                  $open        $high         $low       $close      $volume
datetime
2017-08-17  4261.479980  4485.390137  4200.740234  4285.080078   795.150391
2017-08-18  4285.080078  4371.520020  3938.770020  4108.370117  1199.888306
2017-08-19  4108.370117  4184.689941  3850.000000  4139.979980   381.309753

  ····························································  …

                   $open    $high          $low   $close      $volume
datetime
2026-08-29  77845.882812  78330.0  77382.367188  78230.0  7016.302734
2026-08-30  78230.000000  79400.0  77000.000000  77682.0  9085.423828
2026-08-31  79018.000000  81282.0  76962.000000  77689.0     0.000000

====================================================================
  DOGE
====================================================================
  Filas: 2615  |  Rango: 2019-07-05 → 2026-08-31

               $open     $high      $low    $close       $volume
datetime
2019-07-05  0.004490  0.004600  0.003550  0.003870  1.928298e+09
2019-07-06  0.003874  0.003943  0.003365  0.003500  1.010744e+09
2019-07-07  0.003504  0.003650  0.003400  0.003538  5.306140e+08

  ····························································  …

              $open    $high      $low    $close      $volume
datetime
2026-08-29  0.08525  0.08571  0.084180  0.085290  278519008.0
2026-08-30  0.08530  0.08650  0.080810  0.082050  605824320.0
2026-08-31  0.08768  0.09020  0.081079  0.082127          0.0

====================================================================
  ETH
====================================================================
  Filas: 3302  |  Rango: 2017-08-17 → 2026-08-31

                 $open       $high        $low      $close      $volume
datetime
2017-08-17  301.130005  312.179993  298.000000  302.000000  7030.710449
2017-08-18  302.000000  311.790009  283.940002  293.959991  9537.846680
2017-08-19  293.309998  299.899994  278.000000  290.910004  2146.197754

  ····························································  …

                  $open        $high         $low       $close        $volume
datetime
2026-08-29  2442.790039  2459.760010  2430.449951  2457.669922  103523.921875
2026-08-30  2457.669922  2534.979980  2387.280029  2416.879883  268297.937500
2026-08-31  2506.340088  2558.469971  2394.909912  2417.820068       0.000000

====================================================================
  LINK
====================================================================
  Filas: 2785  |  Rango: 2019-01-16 → 2026-08-31

             $open   $high    $low  $close       $volume
datetime
2019-01-16  0.5355  0.5355  0.4668  0.4895  1.343660e+06
2019-01-17  0.4895  0.4953  0.4639  0.4756  1.411725e+06
2019-01-18  0.4762  0.5112  0.4601  0.4894  9.844176e+05

  ····························································  …

             $open  $high    $low  $close     $volume
datetime
2026-08-29  11.434  11.52  11.280  11.458  1242504.00
2026-08-30  11.458  11.80  10.992  11.144  1668274.25
2026-08-31  11.620  12.05  11.020  11.170        0.00

====================================================================
  LTC
====================================================================
  Filas: 3184  |  Rango: 2017-12-13 → 2026-08-31

                 $open       $high        $low      $close       $volume
datetime
2017-12-13  272.000000  330.000000  260.000000  290.010010   9565.160156
2017-12-14  290.010010  302.720001  252.000000  272.399994   9631.983398
2017-12-15  272.399994  314.209991  239.990005  294.000000  16579.783203

  ····························································  …

            $open      $high       $low     $close        $volume
datetime
2026-08-29  49.32  49.509998  48.500000  49.020000  220710.609375
2026-08-30  49.02  50.130001  47.410000  47.939999  208133.984375
2026-08-31  50.50  50.500000  47.599998  47.939999       0.000000

====================================================================
  SOL
====================================================================
  Filas: 2212  |  Rango: 2020-08-11 → 2026-08-31

             $open   $high    $low  $close     $volume
datetime
2020-08-11  2.8500  3.5208  2.8433  3.2985  1552384.75
2020-08-12  3.2985  3.9289  3.0800  3.7558  1737043.00
2020-08-13  3.7500  4.1387  3.5003  3.7300  1685759.25

  ····························································  …

                 $open       $high        $low      $close    $volume
datetime
2026-08-29  104.139999  105.879997  103.029999  105.610001  1438492.5
2026-08-30  105.610001  107.480003  100.309998  101.750000  2069486.5
2026-08-31  102.050003  110.169998  100.599998  101.860001        0.0

====================================================================
  XLM
====================================================================
  Filas: 3015  |  Rango: 2018-05-31 → 2026-08-31

              $open    $high     $low   $close     $volume
datetime
2018-05-31  0.28021  0.30600  0.28021  0.29568  13858337.0
2018-06-01  0.29567  0.29999  0.27963  0.28863  20363494.0
2018-06-02  0.28869  0.30489  0.28812  0.29740  21831274.0

  ····························································  …

               $open     $high      $low    $close     $volume
datetime
2026-08-29  0.179600  0.180300  0.176800  0.179800  26775272.0
2026-08-30  0.179700  0.182500  0.172400  0.174600  58861180.0
2026-08-31  0.185434  0.189527  0.173018  0.174877         0.0

====================================================================
  XRP
====================================================================
  Filas: 3042  |  Rango: 2018-05-04 → 2026-08-31

             $open  $high     $low   $close     $volume
datetime
2018-05-04  0.5000  1.500  0.50000  0.88990  20890214.0
2018-05-05  0.8898  0.935  0.88800  0.90280  16816166.0
2018-05-06  0.9028  0.918  0.83774  0.86483  16002036.0

  ····························································  …

             $open   $high    $low  $close     $volume
datetime
2026-08-29  1.3838  1.4032  1.3768  1.3964  50379184.0
2026-08-30  1.3964  1.4335  1.3352  1.3575  94998016.0
2026-08-31  1.4200  1.4700  1.3400  1.3600         0.0

✅ Cargadas 9 coins en el dict `dataframes`.

## 4. (Opcional) Doble comprobación: head/tail de las 9 en una sola tabla

Si prefieres ver todas las coins de un vistazo, las cargamos desde su fecha de inicio real, concatenamos en un solo DataFrame (índice `instrument`/`datetime`) y mostramos `head(2)` y `tail(2)` combinados.

In [4]:
import pandas as pd

# Cargamos cada coin desde su fecha real de inicio (así no hay ceros de padding) y concatenamos
frames = [dataframes[c].copy() for c in coins]
for c, df in zip(coins, frames):
    df.index = pd.MultiIndex.from_product([[c.upper()], df.index], names=["instrument", "datetime"])
all_feats = pd.concat(frames)

print("SHAPE TOTAL:", all_feats.shape)
print("\n── HEAD (primeros 2 días de cada coin) ──")
print(all_feats.groupby(level="instrument").head(2))
print("\n── TAIL (últimos 2 días de cada coin) ──")
print(all_feats.groupby(level="instrument").tail(2))

SHAPE TOTAL: (26516, 5)

── HEAD (primeros 2 días de cada coin) ──
                             $open        $high         $low       $close  \
instrument datetime
ADA        2018-04-17     0.255510     0.288000     0.239830     0.242600
           2018-04-18     0.242600     0.264600     0.242010     0.262000
BTC        2017-08-17  4261.479980  4485.390137  4200.740234  4285.080078
           2017-08-18  4285.080078  4371.520020  3938.770020  4108.370117
DOGE       2019-07-05     0.004490     0.004600     0.003550     0.003870
           2019-07-06     0.003874     0.003943     0.003365     0.003500
ETH        2017-08-17   301.130005   312.179993   298.000000   302.000000
           2017-08-18   302.000000   311.790009   283.940002   293.959991
LINK       2019-01-16     0.535500     0.535500     0.466800     0.489500
           2019-01-17     0.489500     0.495300     0.463900     0.475600
LTC        2017-12-13   272.000000   330.000000   260.000000   290.010010
           2017-12-14   290.010010   302.720001   252.000000   272.399994
SOL        2020-08-11     2.850000     3.520800     2.843300     3.298500
           2020-08-12     3.298500     3.928900     3.080000     3.755800
XLM        2018-05-31     0.280210     0.306000     0.280210     0.295680
           2018-06-01     0.295670     0.299990     0.279630     0.288630
XRP        2018-05-04     0.500000     1.500000     0.500000     0.889900
           2018-05-05     0.889800     0.935000     0.888000     0.902800

                            $volume
instrument datetime
ADA        2018-04-17  6.746230e+07
           2018-04-18  3.132810e+07
BTC        2017-08-17  7.951504e+02
           2017-08-18  1.199888e+03
DOGE       2019-07-05  1.928298e+09
           2019-07-06  1.010744e+09
ETH        2017-08-17  7.030710e+03
           2017-08-18  9.537847e+03
LINK       2019-01-16  1.343660e+06
           2019-01-17  1.411725e+06
LTC        2017-12-13  9.565160e+03
           2017-12-14  9.631983e+03
SOL        2020-08-11  1.552385e+06
           2020-08-12  1.737043e+06
XLM        2018-05-31  1.385834e+07
           2018-06-01  2.036349e+07
XRP        2018-05-04  2.089021e+07
           2018-05-05  1.681617e+07

── TAIL (últimos 2 días de cada coin) ──
                              $open         $high          $low        $close  \
instrument datetime
ADA        2026-08-30      0.201800      0.206100      0.189400      0.192700
           2026-08-31      0.212376      0.217739      0.190268      0.192917
BTC        2026-08-30  78230.000000  79400.000000  77000.000000  77682.000000
           2026-08-31  79018.000000  81282.000000  76962.000000  77689.000000
DOGE       2026-08-30      0.085300      0.086500      0.080810      0.082050
           2026-08-31      0.087680      0.090200      0.081079      0.082127
ETH        2026-08-30   2457.669922   2534.979980   2387.280029   2416.879883
           2026-08-31   2506.340088   2558.469971   2394.909912   2417.820068
LINK       2026-08-30     11.458000     11.800000     10.992000     11.144000
           2026-08-31     11.620000     12.050000     11.020000     11.170000
LTC        2026-08-30     49.020000     50.130001     47.410000     47.939999
           2026-08-31     50.500000     50.500000     47.599998     47.939999
SOL        2026-08-30    105.610001    107.480003    100.309998    101.750000
           2026-08-31    102.050003    110.169998    100.599998    101.860001
XLM        2026-08-30      0.179700      0.182500      0.172400      0.174600
           2026-08-31      0.185434      0.189527      0.173018      0.174877
XRP        2026-08-30      1.396400      1.433500      1.335200      1.357500
           2026-08-31      1.420000      1.470000      1.340000      1.360000

                            $volume
instrument datetime
ADA        2026-08-30  1.111736e+08
           2026-08-31  0.000000e+00
BTC        2026-08-30  9.085424e+03
           2026-08-31  0.000000e+00
DOGE       2026-08-30  6.058243e+08
           2026-08-31  0.000000e+00
ETH        2026-08-30  2.682979e+05
           2026-08-31  0.000000e+00
LINK       2026-08-30  1.668274e+06
           2026-08-31  0.000000e+00
LTC        2026-08-30  2.081340e+05
           2026-08-31  0.000000e+00
SOL        2026-08-30  2.069486e+06
           2026-08-31  0.000000e+00
XLM        2026-08-30  5.886118e+07
           2026-08-31  0.000000e+00
XRP        2026-08-30  9.499802e+07
           2026-08-31  0.000000e+00